name: Ediciones Armadillo
favicon: null
layout_spectrum: 0.76447
typography_spectrum: 0.57763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7372'
    - '#000000'
    - '#565656'
    - '#acacac'
  brandStrength: 0.2833818309009075
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
